name: tempbox
description: "A new Flutter project."
publish_to: 'none'
version: 1.2.2+8

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  mailtm_client: ^3.0.1
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  equatable: ^2.0.5
  path_provider: ^2.1.3
  flutter_slidable: ^3.1.1
  macos_ui: ^2.0.2
  url_launcher: ^6.3.0
  window_manager: ^0.3.9
  flutter_widget_from_html_core: ^0.15.1
  fluent_ui: ^4.9.0
  system_theme: ^3.0.0
  file_picker: ^8.0.0+1
  cupertino_modal_sheet: ^1.1.0
  pull_down_button: ^0.9.4
  http: ^1.2.2
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/